# Generated by Django 2.2.3 on 2019-08-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restsharpTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(default='image/default_image.jpeg', upload_to=''),
        ),
    ]
