# Generated by Django 2.2.3 on 2019-08-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetest', '0002_auto_20190805_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
