# Generated by Django 2.2.3 on 2019-08-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetest', '0003_auto_20190806_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
