# Generated by Django 2.2.3 on 2019-08-01 16:29

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('is_teacher', models.BooleanField(default=False)),
                ('school_subject', jsonfield.fields.JSONField(blank=True, null=True)),
                ('school_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('school_class', models.CharField(blank=True, max_length=10, null=True)),
                ('school_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
