# Generated by Django 2.2.3 on 2019-08-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0006_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_subject',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
